create table if not exists public.pokedex_profiles (
  trainer_id text primary key,
  caught_ids integer[] not null default '{}',
  milestones jsonb not null default '{}',
  updated_at timestamp with time zone not null default now()
);

alter table public.pokedex_profiles
  add column if not exists milestones jsonb not null default '{}';

alter table public.pokedex_profiles enable row level security;

drop policy if exists "Public read pokedex profiles" on public.pokedex_profiles;
drop policy if exists "Public insert pokedex profiles" on public.pokedex_profiles;
drop policy if exists "Public update pokedex profiles" on public.pokedex_profiles;

create policy "Public read pokedex profiles"
  on public.pokedex_profiles
  for select
  using (true);

create policy "Public insert pokedex profiles"
  on public.pokedex_profiles
  for insert
  with check (true);

create policy "Public update pokedex profiles"
  on public.pokedex_profiles
  for update
  using (true)
  with check (true);

create table if not exists public.pokedex_journal (
  id bigint generated by default as identity primary key,
  trainer_id text not null,
  event_type text not null default 'caught',
  pokemon_id integer not null,
  pokemon_name text not null,
  happened_at timestamp with time zone not null default now(),
  constraint pokemon_id_range check (pokemon_id between 1 and 2000)
);

alter table public.pokedex_journal drop constraint if exists pokemon_id_range;
alter table public.pokedex_journal
  add constraint pokemon_id_range check (pokemon_id between 1 and 2000);

create index if not exists pokedex_journal_trainer_time_idx
  on public.pokedex_journal (trainer_id, happened_at);

alter table public.pokedex_journal enable row level security;

drop policy if exists "Public read pokedex journal" on public.pokedex_journal;
drop policy if exists "Public insert pokedex journal" on public.pokedex_journal;
drop policy if exists "Public delete pokedex journal" on public.pokedex_journal;

create policy "Public read pokedex journal"
  on public.pokedex_journal
  for select
  using (true);

create policy "Public insert pokedex journal"
  on public.pokedex_journal
  for insert
  with check (true);

create policy "Public delete pokedex journal"
  on public.pokedex_journal
  for delete
  using (true);
